### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by sourav044** [RaRe-Technologies/w2v_server_googlenews#6]
NAN

**Comment by piskvorky** [comment]
Please see the issue template for Gensim. This is not the place for such questions – try the [mailing list](https://groups.google.com/forum/#!forum/gensim).

**Comment by wudejian789** [comment]
I think there are two ways to implement the system. One is to train a word2vec model as usual and thus you can obtain the word embeddings. For each input, design an algorithm to search all of the possible answer from the embedding space. Another one is to train a model with one inout and three output like this. The challange of this way is how to get enough training data.   I think way one is better. The algorithm is not hard to achieve. The simplest search algorithm is to iterate all combination which is time-consuming. Some heuristic search algorithm could be used to optimize the speed and performance. 793729558 ***@***.*** 签名由 网易邮箱大师 定制 On 06/10/2021 23:53, Sourav Kumar wrote: Till now, we have seen the embeddings of analogy "woman is to queen as man is to king." as is represented by Man -> Woman and King -> Queen. We can also find the queen from the equation king - man + woman = ? with the help of word2vec. Now, I wonder, is it possible to find all the analogies with one word. input: queen output: king - man + woman So, the user will input a word queen into the system, and the system should explain the analogy for the word queen. How can we configure such a system and determine the scoring function? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
